server:
  port: 9000


#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///D:/practice/spring/dungi

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/practice/spring/dungi/config-file/server