server:
  port: 9002

spring:

  application:
    name: API-SERVICE

  # config 서버로부터 비밀설정정보 가져오기 (dev/prod)
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      profile: prod

  servlet:
    # 파일 요청 용량 설정
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true

  # 데이터베이스 설정
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3300/spring_dungi
      username: root
      password:
    slave:
      jdbc-url: jdbc:mysql://localhost:3301/spring_dungi
      username: root
      password:

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# redis 설정
redis:
  port: 6300
  host: localhost
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8
  master:
    name: mymaster
  sentinel:
    port1: 26379
    port2: 26380
    port3: 26381



# file 설정
file:
  upload:
    path: /src/main/resources/static/
  down:
    path: http://localhost:9003/static/


# eureka 설정
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

