server:
  port: 9004


spring:

  application:
    name: ROOM-SERVICE

  # config 서버로부터 설정정보 가져오기
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      profile: dev

  # 데이터베이스 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# redis 설정
redis:
  port: 6379
  host: localhost
  lettuce:
    pool:
      max-idle: 8
      min-idle: 2
      max-active: 8
  master:
    name: mymaster
  sentinel:
    port1: 26379
    port2: 26380
    port3: 26381

# eureka 설정
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

